language: python

python:
  - "3.5"

install:
    - pip install -r requirements.txt
    - pip install codecov

script: make test

after_success:
    - codecov --token 7c3b60a8-46be-4bb2-b5ea-67e26b45ecbc

branches:
  only:
  - master

notifications:
  email: false
